_type_: dlcore.configs.roots.training.SegTrainingConfig
batch_size: 4
data:
  train_set:
    csv_name: master_annotations_1k.csv
    dataset_path: /home/alexli/data/Jupiter_train_v5_11/
    dataset_name: Jupiter_train_v5_11
  input_data:
    input_mode: "RGBD"
trainer:
  max_epochs: 1
  logger:
    _type_: dlcore.configs.third_party.logger_config.DummyLoggerConfig
