_type_: dlcore.configs.roots.prediction.SegPredictionConfig
batch_size: 1
data:
  train_set:
    csv_name: master_annotations_100.csv
    dataset_path: /data/jupiter/datasets/Jupiter_train_v5_11_20230508
predictor:
  logger:
    _type_: dlcore.configs.third_party.logger_config.DummyLoggerConfig
model_file: /mnt/sandbox1/alex.li/wandb/wandb/run-20231018_184348-4c26c094/files/epoch=99-val_acc=0.000000-val_loss=0.050370.ckpt
