_type_: kore.configs.roots.training.SegTrainingConfig
batch_size: 4
data:
  train_set:
    csv_name: master_annotations_4k.csv
    dataset_path: /home/alexli/data/Jupiter_train_v5_11/
    dataset_name: Jupiter_train_v5_11
  validation_set: null
  validation_set_ratio: .25
trainer:
  max_epochs: 2
  # logger:
  #   _type_: kore.configs.third_party.logger_config.DummyLoggerConfig
output_dir: '/home/alexli/logs/data/$RUN_ID'
run_id: my_test_run
# ckpt_path: /home/alexli/logs/data/epoch=99-val_loss=0.096904.ckpt
# warm_up_steps: 100
