_type_: kore.configs.roots.training.DepthTrainingConfig
batch_size: 8
data:
  train_set:
    csv_name: master_annotations_1k.csv
    dataset_path: /home/alexli/data/Jupiter_train_v5_11/
    dataset_name: Jupiter_train_v5_11
trainer:
  max_epochs: 1
  logger:
    _type_: kore.configs.third_party.logger_config.DummyLoggerConfig
  callbacks:
    model_checkpoint:
      dirpath: /home/alexli/logs/depth_checkpoints
