_type_: kore.configs.roots.training.SegTrainingConfig
data:
  train_set:
    csv_name: master_annotations.csv
    dataset_path: /data2/jupiter/datasets/Jupiter_train_v6_2
lr_scheduler:
  _type_: kore.configs.third_party.lr_scheduler_config.CosineAnnealingLRConfig
batch_size: 16
optimizer:
  _type_: kore.configs.third_party.optimizer_config.AdamWConfig
  betas: [0.9, 0.999]
  lr: 1e-3
