_type_: kore.configs.roots.training.SegTrainingConfig
batch_size: 1
augmentation:
  cnp:
    use: false
inputs:
  input_mode: RGBD
trainer:
  logger:
    _type_: kore.configs.third_party.logger_config.DummyLoggerConfig
