_type_: kore.configs.roots.prediction.SegPredictionConfig
predictor:
  logger:
    _type_: kore.configs.third_party.logger_config.DummyLoggerConfig
batch_size: 32
data:
  test_set:
    csv: master_annotations_subset.csv
    dataset_path: /home/avinashraju/BRT/data/Jupiter_train_v5_11_subset_1
    num_workers: 24
