_type_: kore.configs.roots.training.SegTrainingConfig
batch_size: 1
augmentation:
  cnp:
    use: false
trainer:
  logger:
    _type_: kore.configs.third_party.logger_config.DummyLoggerConfig
  precision: "32"