_type_: kore.configs.roots.training.SegTrainingConfig
optimizer:
  _type_: kore.configs.third_party.optimizer_config.SAMConfig
  lr: 6e-4
  rho: 1.0
  adaptive: False
trainer:
  strategy:
    _type_: kore.configs.third_party.strategy_config.DDPStrategyConfig
    find_unused_parameters: true
  precision: '32'
  max_epochs: 20
  num_sanity_val_steps: 0
  callbacks:
    tqdm: False
finetuning:
  fine_tune_lr: 0.0
model:
  _type_: kore.configs.tasks.semantic_segmentation.model_config.BRTResnetPyramidLite12Config
  model_params:
    upsample_mode: 'area'
  dust:
    dust_seg_output: true
