augmentation:
  # albumentation_transform_path: $CVML_DIR/kore/configs/data/albumentations/seg_trivialaugment.yml
  albumentation_transform_path: /home/alex.li/git/scripts/training/ben_albumentations.yml
  cnp:
    use: false
data:
  train_set:
    csv: master_annotations_dedup.csv
    dataset_path: /data2/jupiter/datasets/halo_rgb_stereo_train_v6_1
  validation_set:
    csv: master_anno_val.csv
    dataset_path: /data2/jupiter/datasets/halo_rgb_stereo_train_v6_1
    absolute_csv: False
batch_size: 32
inputs:
  label:
    half_res_output: true
loss:
  msl:
    alpha: [4.0,1.0,1.0,1.0,5.0,4.0,1.0,1.0]
    epsilon: 1e-6
  msl_weight: 18.0
  tv:
    fp_weight:    [0.6,0.3,0.6,0.6,0.6,0.7,0.3,0.6]
    fn_weight:    [0.7,0.7,0.4,0.4,2.0,2.8,0.7,0.4]
    class_weight: [1.0,2.0,1.0,1.0,2.0,2.0,5.0,1.0]
  tv_weight: 1.0
  prodl:
    prob_thresh: -1.0
  prodl_weight: 7.0
optimizer:
  _type_: kore.configs.third_party.optimizer_config.AdamWConfig
  lr: 1e-3
  weight_decay: 1e-3
trainer:
  max_epochs: 70
  enable_early_stopping: false
  precision: "16-mixed"
model:
  _type_: kore.configs.tasks.semantic_segmentation.model_config.BRTResnetPyramidLite12Config
  half_res_output: true
lr_scheduler:
  _type_: kore.configs.third_party.lr_scheduler_config.CosineAnnealingLRConfig
upload_epoch_ckpts: true
warm_up_steps: 0
weighted_sampling: {airborne_debris: 1.0, birds: 1.0, day_vehicles: 1.0, humans: 1.0,
  night_vehicles: 1.0, occluded_humans: 1.0, reverse_humans: 1.0, tiny_humans: 1.0,
  tiny_vehicles: 1.0, triangle_humans: 1.0}
