wandb_version: 1

dataset:
  desc: null
  value: jupiter-farmfield-v1.9
losses:
  desc: null
  value:
    msl: 1.0
    tv: 1.0
    prodl: 0.02
optimizer:
  desc: null
  value: adamw
model:
  desc: null
  value: brtresnetpyramid
model_params:
  desc: null
  value:
    num_block_layers: 2
    widening_factor: 2
    upsample_mode: nearest
    bias: true
dust_output_params:
  desc: null
  value:
    dust_head_output: true
    dust_class_ratio: false
    dust_class_confidence_map: false
    zero_dust_ratio: false
    dust_head_output_multiplier: 100
    dust_head_output_threshold: 10
    threshold_on_dust_channel: 0.35
no_intermediate_embeddings:
  desc: null
  value: false
data_dir:
  desc: null
  value: /data/jupiter/datasets/Jupiter_train_v5_11/
csv_path:
  desc: null
  value: /data/jupiter/li.yu/data/Jupiter_train_v5_11/epoch0_5_30_focal05_master_annotations.csv
csv_path_validation:
  desc: null
  value: null
output_dir:
  desc: null
  value: /data/jupiter/alex.li/test/results
save_pred_every:
  desc: null
  value: 2500
snapshot_dir:
  desc: null
  value: test/d5d7e14e
batch_size:
  desc: null
  value: 32
fp16:
  desc: null
  value: false
ignore_label:
  desc: null
  value: 255
input_size:
  desc: null
  value:
  - 512
  - 1024
input_mode:
  desc: null
  value: RGBD
input_dims:
  desc: null
  value: 4
is_training:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 0.001
fine_tune_lr:
  desc: null
  value: 0
momentum:
  desc: null
  value: 0.9
start_iters:
  desc: null
  value: 0
num_steps:
  desc: null
  value: 100000
power:
  desc: null
  value: 0.9
restore_from:
  desc: null
  value: ''
resume_from_snapshot:
  desc: null
  value: false
save_num_images:
  desc: null
  value: 2
val_set_ratio:
  desc: null
  value: 0.2
val_set_metrics:
  desc: null
  value: true
early_stop_patience:
  desc: null
  value: 7
weight_decay:
  desc: null
  value: 0.001
night_model:
  desc: null
  value:
    use: true
    dark_pix_threshold: 10
gpu:
  desc: null
  value: all
num_workers:
  desc: null
  value: 64
seed:
  desc: null
  value: 304
store_output:
  desc: null
  value: 'False'
epochs:
  desc: null
  value: 50
eval:
  desc: null
  value: false
fix_lr:
  desc: null
  value: false
log_file:
  desc: null
  value: ''
epsilon:
  desc: null
  value: 1.0e-06
color_jitter:
  desc: null
  value:
    brightness: 0.1
    contrast: 0
    saturation: 0.2
    hue: 0.3
trivial_augment:
  desc: null
  value:
    use: true
lr_scheduler_name:
  desc: null
  value: cosinelr
lr_scheduler_parameters:
  desc: null
  value:
    steplr_step_size: 7
    steplr_gamma: 0.1
    cosinelr_T_max: 30
    cosinelr_eta_min: 1.0e-06
focalloss_parameters:
  desc: null
  value:
    alpha:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    gamma: 2.0
tversky_parameters:
  desc: null
  value:
    fp_weight:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    fn_weight:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    class_weight:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    gamma: 1.0
huberloss_beta:
  desc: null
  value: 1.0
equalizationloss_parameters:
  desc: null
  value:
    T:
    - 0.0
    - 1.0
    - 0.0
    - 0.0
productivity_loss_params:
  desc: null
  value:
    depth_thresh: 0.35
    prob_thresh: 0.01
multiscaleloss_weight:
  desc: null
  value: 0.1
multiscalemixedloss_parameters:
  desc: null
  value:
    scale_weight: 0.1
    dust_weight: 0.5
    dust_scale_weight: 0.05
run_id:
  desc: null
  value: d5d7e14e
focalloss_expdecay:
  desc: null
  value:
    use: false
    exp_min: 1
    exp_max: 10
adj_img_gamma:
  desc: null
  value:
    use: false
    gamma_low: 0.3
    gamma_high: 0.9
    gain_low: 0.5
    gain_high: 1.2
adj_color_temp:
  desc: null
  value:
    use: false
    temp_low: 2001
    temp_high: 15000
save_states_visualizations:
  desc: null
  value: true
exp_name:
  desc: null
  value: test
states_to_save:
  desc: null
  value:
  - true_positive
  - true_negative
  - false_positive
  - false_negative
  - large_object_true_positive
  - large_object_false_negative
  - human_true_positive
  - human_true_negative
  - human_false_positive
  - human_false_negative
  - vehicle_true_positive
  - vehicle_true_negative
  - vehicle_false_positive
  - vehicle_false_negative
gt_stop_classes_to_consider:
  desc: null
  value:
  - Humans
checkpoint_metric:
  desc: null
  value: val/loss
s3_checkpoint_path:
  desc: null
  value: ''
human_augmentation:
  desc: null
  value:
    use: false
normalization_params:
  desc: null
  value:
    policy: tonemap
    alpha: 0.25
    beta: 0.9
    gamma: 0.9
    eps: 1.0e-06
label_map_file:
  desc: null
  value: /home/alex.li/git/JupiterCVML/europa/base/src/europa/dl/config/label_maps/four_class_train.csv
run_pre_val:
  desc: null
  value: false
save_data_sample:
  desc: null
  value: false
val_csv:
  desc: null
  value: /home/alex.li/git/JupiterCVML/europa/base/src/europa/dl/config/val_ids/Jupiter_val_ids_v4_63_geohash.csv
weighted_sampling:
  desc: null
  value:
    birds: 1.0
    humans: 1.0
    reverse_humans: 3.0
hard_sampling:
  desc: null
  value:
    use: false
    warmup_epochs: 2
    min_pix_count: 200
    gamma: 1.0
    multiplier: 4.0
    safety_max_weight: 20.0
    productivity: true
    depth_threshold: 0.25
    max_area_denominator: 2000
    productivity_max_weight: 20.0
skip_mismatched_layers:
  desc: null
  value: false
half_res_output:
  desc: null
  value: false
use_albumentation_transform:
  desc: null
  value: false
threshold_min_pixels:
  desc: null
  value: 400
use_depth_threshold:
  desc: null
  value: false
side_left_tire_mask:
  desc: null
  value: /home/alex.li/git/JupiterCVML/europa/base/src/europa/dl/config/tire_masks/side_left_mask.png
side_right_tire_mask:
  desc: null
  value: /home/alex.li/git/JupiterCVML/europa/base/src/europa/dl/config/tire_masks/side_right_mask.png
dust_mask:
  desc: null
  value: NO MASK INVALID PATH
flip_lo_pixels:
  desc: null
  value: false
confidence_threshold:
  desc: null
  value: 0.8
run_productivity_metrics:
  desc: null
  value: true
test_time_augmentation:
  desc: null
  value: false
merge_stop_class_confidence_threshold:
  desc: null
  value: -1
depth_thresholds:
  desc: null
  value:
    front: 0.12
    side: 0.14
    rear: 0.25
vat:
  desc: null
  value: false
dust_class_metrics:
  desc: null
  value: true
tqdm:
  desc: null
  value: false
notes:
  desc: null
  value: null
pred_tag:
  desc: null
  value: ''
num_classes:
  desc: null
  value: 4
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.5
    framework: huggingface
    huggingface_version: 4.30.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689712163.559177
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 80
      3:
      - 1
      - 13
      - 14
      - 16
      - 23
      4: 3.10.12
      5: 0.15.5
      6: 4.30.2
      8:
      - 5
